name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build_and_push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ui
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.ui
          push: true
          tags: ghcr.io/snipercam/cvat-ui:${{ github.event.release.tag_name }}

      - name: Build and push server
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/snipercam/cvat-server:${{ github.event.release.tag_name }}
